---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: docs/.vuepress
  label: Config
  create: all
  match: "**/*"
- type: directory
  path: docs
  label: Docs
  create: all
  match: "**/*"
  new_doc_ext: md
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: npm run build-docs
  publish_command: npm run build-docs
  output_directory: docs/.vuepress/dist
